### ISSUE TITLE
including interaction term between alternative and individual specific variables

### ISSUE THREAD

**Issue by albertostefanelli** [kosukeimai/MNP#5]
I am wondering if it is possible to include an interaction term between an alternative specific variable and an individual specific variable such as implemented in the package mlogit

**Comment by kosukeimai** [comment]
Yes, you can.  You just have to add a bunch of zeros for the dimensions corresponding to the other alternatives so that the interaction term only affects a specific dimension.

**Comment by albertostefanelli** [comment]
thanks for your answer kosukeimai! This helped me a lot! 
Can I interact an alternative specific variable with an individual specific variable and getting specific coefficient instead of a generic one. In a context with a DV with 3 categories with 3 alternative specific variables and 1 individual specific variable one would be: 

DV_category_1 ON  Utility_1 X Invididual non-varying characteristic (such as age)
DV_category_2 ON Utility_2 X Invididual non-varying characteristic (such as age)
DV_category_3 ON Utility_3 X Invididual non-varying characteristic (such as age)

A syntax example would be also really appreciated : )

**Comment by kosukeimai** [comment]
Yes you can do that as well.

**Comment by albertostefanelli** [comment]
Can you provide an example of syntax? I am not able to figure it out by myself and it seems there is no example on the guide. Many thanks !

**Comment by kosukeimai** [comment]
Take a look at Slide 17 of https://imai.fas.harvard.edu/teaching/files/discrete.pdf which shows how to construct the design matrix.

**Comment by albertostefanelli** [comment]
I understood the principles behind but the package returns the coefficients for each choice indicator variable which is not what i am looking for. I would like a single coefficient for each category as achieved in mlogit with the formula` mlogit(3_category_choice ~ 0 |0| alternative_specific_utility, your_data)`

The syntax used for mnp is the following: 

```
model_1 <- mnp(3_category_choice ~ utility_1_dummy + 
  utility_2_dummy+ 
  utility_3_dummy,
  data = data,
  verbose = TRUE)
```

Where

3_category_choice is a character identifier of the choice (such as bus, train or car). 
utility_1_dummy is a numeric score that signals the individual utility for using the bus. If the respondent did not choose the first category (bus) this is set to 0 
utility_2_dummy same for train 
utility_2_dummy same for car
