### ISSUE TITLE
question: how to forecast for new data

### ISSUE THREAD

**Issue by lanealencar** [kosukeimai/MNP#6]
I taught that the option new.data would allow the calculation of the probabilities for newdata. then I receive a message
Warning message:
'newdata' had 31 rows but variables found have 5938 rows 
how to obtain the predictive distribution for these new data.
Thank you

**Comment by kosukeimai** [comment]
Please see: https://cran.r-project.org/web/packages/MNP/vignettes/MNP.pdf
